source 'https://rubygems.org'

ruby '~> 3.2.4'

gem 'rails', '~> 5.2.6'

gem "aruba"
gem "bcrypt", '~> 3.1.8'
gem "execjs"
gem "foreman"
gem "jquery-fileupload-rails"
gem "minitest"
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'sidekiq-unique-jobs', '>=8.0.0', '<8.0.7', require: true
# Pin Puma to a recent-ish version that supports OpenSSL, which is
# what the CircleCI environment has.
gem 'puma', '~> 5.5'
gem 'camaleon_cms', '2.7.4'

group :test do
  gem 'capybara', '~>3.35'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'percy-capybara', '~> 4.3.3'
end

group :production do
  gem 'rails_12factor'
  gem 'dragonfly', '~> 1.2.1'
end